#ifndef __MODEL_CONSTANTS_H__
#define __MODEL_CONSTANTS_H__

#include <stddef.h>

/*
 * This file is generated by constants.py
 */

static const struct model buhlmann_zh_l16c_nitrogen = {
	.name = "Buhlmann ZH-L16C Nitrogen",
	.count = 17,
	.compartments = {
		{.halftime = 240.0, .mvalue = 1.332, .mslope = 1.9082},
		{.halftime = 300.0, .mvalue = 1.167, .mslope = 1.7928},
		{.halftime = 480.0, .mvalue = 1.005, .mslope = 1.5352},
		{.halftime = 750.0, .mvalue = 0.865, .mslope = 1.3847},
		{.halftime = 1110.0, .mvalue = 0.752, .mslope = 1.2780},
		{.halftime = 1620.0, .mvalue = 0.619, .mslope = 1.2306},
		{.halftime = 2298.0, .mvalue = 0.504, .mslope = 1.1857},
		{.halftime = 3258.0, .mvalue = 0.440, .mslope = 1.1504},
		{.halftime = 4620.0, .mvalue = 0.398, .mslope = 1.1223},
		{.halftime = 6540.0, .mvalue = 0.370, .mslope = 1.0999},
		{.halftime = 8760.0, .mvalue = 0.346, .mslope = 1.0844},
		{.halftime = 11220.0, .mvalue = 0.327, .mslope = 1.0731},
		{.halftime = 14340.0, .mvalue = 0.306, .mslope = 1.0635},
		{.halftime = 18300.0, .mvalue = 0.285, .mslope = 1.0552},
		{.halftime = 23400.0, .mvalue = 0.262, .mslope = 1.0478},
		{.halftime = 29880.0, .mvalue = 0.249, .mslope = 1.0414},
		{.halftime = 38100.0, .mvalue = 0.234, .mslope = 1.0359},
	},
};

static const struct model buhlmann_zh_l16a_helium = {
	.name = "Buhlmann ZH-L16A Helium",
	.count = 17,
	.compartments = {
		{.halftime =  90.6, .mvalue = 1.744, .mslope = 2.3557},
		{.halftime = 112.8, .mvalue = 1.624, .mslope = 2.0964},
		{.halftime = 181.2, .mvalue = 1.380, .mslope = 1.7400},
		{.halftime = 283.2, .mvalue = 1.188, .mslope = 1.5321},
		{.halftime = 419.4, .mvalue = 1.046, .mslope = 1.3845},
		{.halftime = 612.6, .mvalue = 0.921, .mslope = 1.3189},
		{.halftime = 868.8, .mvalue = 0.823, .mslope = 1.2568},
		{.halftime = 1231.8, .mvalue = 0.732, .mslope = 1.2079},
		{.halftime = 1746.6, .mvalue = 0.651, .mslope = 1.1692},
		{.halftime = 2472.0, .mvalue = 0.598, .mslope = 1.1419},
		{.halftime = 3311.4, .mvalue = 0.557, .mslope = 1.1232},
		{.halftime = 4241.4, .mvalue = 0.528, .mslope = 1.1115},
		{.halftime = 5420.4, .mvalue = 0.518, .mslope = 1.1022},
		{.halftime = 6917.4, .mvalue = 0.514, .mslope = 1.0963},
		{.halftime = 8845.2, .mvalue = 0.520, .mslope = 1.0904},
		{.halftime = 7094.4, .mvalue = 0.515, .mslope = 1.0850},
		{.halftime = 14401.8, .mvalue = 0.511, .mslope = 1.0791},
	},
};

static const struct model dsat_rdp = {
	.name = "DSAT RDP",
	.count = 14,
	.compartments = {
		{.halftime = 300.0, .mvalue = 2.042, .mslope = 1.0000},
		{.halftime = 600.0, .mvalue = 1.537, .mslope = 1.0000},
		{.halftime = 1200.0, .mvalue = 1.054, .mslope = 1.0000},
		{.halftime = 1800.0, .mvalue = 0.834, .mslope = 1.0000},
		{.halftime = 2400.0, .mvalue = 0.711, .mslope = 1.0000},
		{.halftime = 3600.0, .mvalue = 0.579, .mslope = 1.0000},
		{.halftime = 4800.0, .mvalue = 0.511, .mslope = 1.0000},
		{.halftime = 6000.0, .mvalue = 0.469, .mslope = 1.0000},
		{.halftime = 7200.0, .mvalue = 0.441, .mslope = 1.0000},
		{.halftime = 9600.0, .mvalue = 0.406, .mslope = 1.0000},
		{.halftime = 12000.0, .mvalue = 0.384, .mslope = 1.0000},
		{.halftime = 14400.0, .mvalue = 0.369, .mslope = 1.0000},
		{.halftime = 21600.0, .mvalue = 0.345, .mslope = 1.0000},
		{.halftime = 28800.0, .mvalue = 0.333, .mslope = 1.0000},
	},
};

const struct model *models[] = {
	&buhlmann_zh_l16c_nitrogen,
	&buhlmann_zh_l16a_helium,
	&dsat_rdp,
	NULL,
};

#endif /* __MODEL_CONSTANTS_H__ */
